//! Compile-time scrape of community-curated BGM track names.
//!
//! Reads `vendor/AltanaListener/AltanaListener/track_names.json` (a JSON
//! map of `sound{N}_music{XXX}.bgw → {TrackName, TrackAuthor, ...}`),
//! extracts the (track_id, TrackName, TrackAuthor) triples, and emits
//! a `MUSIC_CATALOG: &[(u16, &str, &str)]` constant the runtime can
//! `lookup` against.
//!
//! Why a build-time scrape (not runtime JSON loading): the generated
//! table compiles into the binary, so the music label is available
//! without depending on the AltanaListener checkout at runtime — and
//! the cost is paid once per build, not on every BGM change.
//!
//! Source attribution: track names + composer credits are maintained
//! by Voliathon in the community AltanaListener project. The numeric
//! id is SE's; the human name is Voliathon's curation. Used here
//! under cite-only convention (the upstream has no LICENSE file but
//! its README declares the project "completely open-source"). See
//! [[altanalistener_no_license]] memory entry for the same caution
//! pattern as `[[xi_tinkerer_agpl_reference]]`.

use std::fs;
use std::path::PathBuf;

const ALTANA_TRACKS: &str =
    "../vendor/AltanaListener/AltanaListener/track_names.json";

fn main() {
    println!("cargo:rerun-if-changed={ALTANA_TRACKS}");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir =
        PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR env var"));

    let entries = match scrape() {
        Ok(v) => v,
        Err(e) => {
            // Don't hard-fail builds when the vendor submodule isn't
            // checked out — emit an empty table and a warning so the
            // crate still compiles in lean environments (e.g., a CI
            // job that didn't `git submodule update --init`).
            println!(
                "cargo:warning=ffxi-audio: music catalog scrape skipped: {e}"
            );
            Vec::new()
        }
    };

    let mut out = String::new();
    out.push_str(
        "// AUTO-GENERATED by ffxi-audio/build.rs — do not edit.\n",
    );
    out.push_str(
        "// Source: vendor/AltanaListener (community-curated track names).\n\n",
    );
    out.push_str(
        "/// Triples of `(track_id, track_name, composer_name)`. Same\n\
         /// `track_id` may legitimately appear in multiple `sound{N}_`\n\
         /// directories on disk; this table deduplicates to one row per\n\
         /// id (first occurrence wins).\n",
    );
    out.push_str(
        "pub const MUSIC_CATALOG: &[(u16, &str, &str)] = &[\n",
    );
    for (id, name, author) in &entries {
        // Rust string escaping for double quotes + backslashes.
        let name_e = escape(name);
        let author_e = escape(author);
        out.push_str(&format!(
            "    ({id}, \"{name_e}\", \"{author_e}\"),\n"
        ));
    }
    out.push_str("];\n");

    fs::write(out_dir.join("music_catalog_table.rs"), &out)
        .expect("write music catalog");

    println!(
        "cargo:warning=ffxi-audio: scraped {} music catalog entries",
        entries.len()
    );
}

/// Minimal scraper. Avoids pulling serde just for build-time JSON: the
/// file is well-formed and ~30 KB, and we only need three fields per
/// entry. Lines we care about have the shape:
///
/// ```text
///   "sound_music101.bgw": {
///     "TrackName": "Battle Theme",
///     "TrackAuthor": "Naoshi Mizuta",
///     ...
///   },
/// ```
///
/// State machine: track the most recent BGW key seen, then capture
/// `TrackName` + `TrackAuthor` on subsequent lines until the next
/// BGW key (or end of file).
fn scrape() -> Result<Vec<(u16, String, String)>, String> {
    let src = fs::read_to_string(ALTANA_TRACKS)
        .map_err(|e| format!("read {ALTANA_TRACKS}: {e}"))?;

    let mut out: Vec<(u16, String, String)> = Vec::new();
    let mut seen: std::collections::HashSet<u16> =
        std::collections::HashSet::new();
    let mut cur_id: Option<u16> = None;
    let mut cur_name: Option<String> = None;
    let mut cur_author: Option<String> = None;

    let flush = |out: &mut Vec<(u16, String, String)>,
                 seen: &mut std::collections::HashSet<u16>,
                 id: &mut Option<u16>,
                 name: &mut Option<String>,
                 author: &mut Option<String>| {
        if let (Some(i), Some(n)) = (id.take(), name.take()) {
            if seen.insert(i) {
                out.push((i, n, author.take().unwrap_or_default()));
            } else {
                // Duplicate ids across sound{N}_ dirs — first wins.
                let _ = author.take();
            }
        } else {
            // No full row yet; drop partials.
            let _ = name.take();
            let _ = author.take();
        }
    };

    for line in src.lines() {
        let trimmed = line.trim();
        // BGW key line opens a new entry.
        if let Some(id) = extract_bgw_id(trimmed) {
            flush(
                &mut out,
                &mut seen,
                &mut cur_id,
                &mut cur_name,
                &mut cur_author,
            );
            cur_id = Some(id);
            continue;
        }
        if let Some(val) = extract_str_field(trimmed, "TrackName") {
            cur_name = Some(val);
            continue;
        }
        if let Some(val) = extract_str_field(trimmed, "TrackAuthor") {
            cur_author = Some(val);
            continue;
        }
    }
    flush(
        &mut out,
        &mut seen,
        &mut cur_id,
        &mut cur_name,
        &mut cur_author,
    );

    out.sort_by_key(|(id, _, _)| *id);
    Ok(out)
}

/// `"sound_music101.bgw": {` or `"sound2_music101.bgw": {` →
/// `Some(101)`. Returns `None` on any other shape.
fn extract_bgw_id(line: &str) -> Option<u16> {
    let bytes = line.as_bytes();
    if bytes.first() != Some(&b'"') {
        return None;
    }
    let key_end = line[1..].find('"').map(|p| p + 1)?;
    let key = &line[1..key_end];
    let stem = key
        .strip_prefix("sound")
        .and_then(|s| {
            // Optional digit(s) before "_music" (sound2_, sound15_, …).
            let rest = s.trim_start_matches(|c: char| c.is_ascii_digit());
            rest.strip_prefix("_music")
        })?;
    let id_part = stem.strip_suffix(".bgw")?;
    id_part.parse::<u16>().ok()
}

/// `"FieldName": "value",` → `Some("value")`. Strips trailing
/// comma/whitespace.
fn extract_str_field(line: &str, field: &str) -> Option<String> {
    let needle = format!("\"{field}\":");
    let rest = line.strip_prefix(&needle)?.trim_start();
    let s = rest.strip_prefix('"')?;
    let end = s.find('"')?;
    Some(s[..end].to_string())
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
