use std::fs;
use std::path::PathBuf;

const ALTANA_TRACKS: &str = "../vendor/AltanaListener/AltanaListener/track_names.json";

fn main() {
    println!("cargo:rerun-if-changed={ALTANA_TRACKS}");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR env var"));

    let entries = match scrape() {
        Ok(v) => v,
        Err(e) => {
            println!("cargo:warning=ffxi-audio: music catalog scrape skipped: {e}");
            Vec::new()
        }
    };

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by ffxi-audio/build.rs — do not edit.\n");
    out.push_str("// Source: vendor/AltanaListener (community-curated track names).\n\n");
    out.push_str(
        "/// Triples of `(track_id, track_name, composer_name)`. Same\n\
         /// `track_id` may legitimately appear in multiple `sound{N}_`\n\
         /// directories on disk; this table deduplicates to one row per\n\
         /// id (first occurrence wins).\n",
    );
    out.push_str("pub const MUSIC_CATALOG: &[(u16, &str, &str)] = &[\n");
    for (id, name, author) in &entries {
        let name_e = escape(name);
        let author_e = escape(author);
        out.push_str(&format!("    ({id}, \"{name_e}\", \"{author_e}\"),\n"));
    }
    out.push_str("];\n");

    fs::write(out_dir.join("music_catalog_table.rs"), &out).expect("write music catalog");

    println!(
        "cargo:warning=ffxi-audio: scraped {} music catalog entries",
        entries.len()
    );
}

fn scrape() -> Result<Vec<(u16, String, String)>, String> {
    let src =
        fs::read_to_string(ALTANA_TRACKS).map_err(|e| format!("read {ALTANA_TRACKS}: {e}"))?;

    let mut out: Vec<(u16, String, String)> = Vec::new();
    let mut seen: std::collections::HashSet<u16> = std::collections::HashSet::new();
    let mut cur_id: Option<u16> = None;
    let mut cur_name: Option<String> = None;
    let mut cur_author: Option<String> = None;

    let flush = |out: &mut Vec<(u16, String, String)>,
                 seen: &mut std::collections::HashSet<u16>,
                 id: &mut Option<u16>,
                 name: &mut Option<String>,
                 author: &mut Option<String>| {
        if let (Some(i), Some(n)) = (id.take(), name.take()) {
            if seen.insert(i) {
                out.push((i, n, author.take().unwrap_or_default()));
            } else {
                let _ = author.take();
            }
        } else {
            let _ = name.take();
            let _ = author.take();
        }
    };

    for line in src.lines() {
        let trimmed = line.trim();

        if let Some(id) = extract_bgw_id(trimmed) {
            flush(
                &mut out,
                &mut seen,
                &mut cur_id,
                &mut cur_name,
                &mut cur_author,
            );
            cur_id = Some(id);
            continue;
        }
        if let Some(val) = extract_str_field(trimmed, "TrackName") {
            cur_name = Some(val);
            continue;
        }
        if let Some(val) = extract_str_field(trimmed, "TrackAuthor") {
            cur_author = Some(val);
            continue;
        }
    }
    flush(
        &mut out,
        &mut seen,
        &mut cur_id,
        &mut cur_name,
        &mut cur_author,
    );

    out.sort_by_key(|(id, _, _)| *id);
    Ok(out)
}

fn extract_bgw_id(line: &str) -> Option<u16> {
    let bytes = line.as_bytes();
    if bytes.first() != Some(&b'"') {
        return None;
    }
    let key_end = line[1..].find('"').map(|p| p + 1)?;
    let key = &line[1..key_end];
    let stem = key.strip_prefix("sound").and_then(|s| {
        let rest = s.trim_start_matches(|c: char| c.is_ascii_digit());
        rest.strip_prefix("_music")
    })?;
    let id_part = stem.strip_suffix(".bgw")?;
    id_part.parse::<u16>().ok()
}

fn extract_str_field(line: &str, field: &str) -> Option<String> {
    let needle = format!("\"{field}\":");
    let rest = line.strip_prefix(&needle)?.trim_start();
    let s = rest.strip_prefix('"')?;
    let end = s.find('"')?;
    Some(s[..end].to_string())
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
