use std::{fs, path::PathBuf};

use anyhow::{bail, Context, Result};

const ZONELINES_SQL: &str = "../vendor/server/sql/zonelines.sql";

fn main() -> Result<()> {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={ZONELINES_SQL}");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").context("OUT_DIR not set")?);

    let src =
        fs::read_to_string(ZONELINES_SQL).with_context(|| format!("reading {ZONELINES_SQL}"))?;
    let mut entries = parse_zonelines(&src)?;

    entries.sort_by_key(|z| z.from_zone);

    let mut index: Vec<(u16, u32, u32)> = Vec::new();
    let mut i = 0u32;
    while (i as usize) < entries.len() {
        let zone = entries[i as usize].from_zone;
        let start = i;
        while (i as usize) < entries.len() && entries[i as usize].from_zone == zone {
            i += 1;
        }
        index.push((zone, start, i));
    }

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by ffxi-nav/build.rs from zonelines.sql.\n");
    out.push_str("// Do not edit by hand.\n\n");

    out.push_str("#[allow(clippy::approx_constant)]\n");
    out.push_str("pub const ZONE_LINES: &[ZoneLine] = &[\n");
    for z in &entries {
        out.push_str(&format!(
            "    ZoneLine {{ line_id: {}, from_zone: {}, from_pos: [{}f32, {}f32, {}f32], to_zone: {}, to_pos: [{}f32, {}f32, {}f32], scale_x: {}f32, scale_z: {}f32, rotation: {}f32 }},\n",
            z.line_id,
            z.from_zone,
            z.from_pos[0], z.from_pos[2], z.from_pos[1],
            z.to_zone,
            z.to_pos[0], z.to_pos[2], z.to_pos[1],
            z.scale_x, z.scale_z, z.rotation,
        ));
    }
    out.push_str("];\n\n");

    out.push_str("/// `(from_zone, start, end)` triples — one per distinct `from_zone`,\n");
    out.push_str("/// where `ZONE_LINES[start..end]` are that zone's outbound lines.\n");
    out.push_str("pub const ZONE_LINE_INDEX: &[(u16, u32, u32)] = &[\n");
    for (zone, start, end) in &index {
        out.push_str(&format!("    ({zone}, {start}, {end}),\n"));
    }
    out.push_str("];\n");

    fs::write(out_dir.join("zonelines_table.rs"), &out)?;
    println!(
        "cargo:warning=ffxi-nav: scraped {} zone-lines across {} from_zones",
        entries.len(),
        index.len()
    );

    Ok(())
}

#[derive(Debug)]
struct ParsedLine {
    line_id: u32,
    from_zone: u16,
    from_pos: [f32; 3],
    to_zone: u16,
    to_pos: [f32; 3],
    scale_x: f32,
    scale_z: f32,
    rotation: f32,
}

fn parse_zonelines(src: &str) -> Result<Vec<ParsedLine>> {
    const PREFIX: &str = "INSERT INTO `zonelines` VALUES (";
    let mut out = Vec::new();
    for (lineno, line) in src.lines().enumerate() {
        let trimmed = line.trim_start();
        let Some(rest) = trimmed.strip_prefix(PREFIX) else {
            continue;
        };
        let Some(end) = rest.find(')') else {
            bail!("zonelines.sql line {}: no closing `)`", lineno + 1);
        };
        let body = &rest[..end];
        let fields: Vec<&str> = body.split(',').map(str::trim).collect();
        if fields.len() != 12 {
            bail!(
                "zonelines.sql line {}: expected 12 fields, got {}",
                lineno + 1,
                fields.len()
            );
        }
        let line_id: u32 = fields[0].parse().with_context(|| {
            format!(
                "zonelines.sql line {}: bad zonelineid `{}`",
                lineno + 1,
                fields[0]
            )
        })?;
        let from_zone: u16 = fields[1].parse().with_context(|| {
            format!(
                "zonelines.sql line {}: bad from_zone `{}`",
                lineno + 1,
                fields[1]
            )
        })?;
        let from_x: f32 = fields[2].parse()?;
        let from_y: f32 = fields[3].parse()?;
        let from_z: f32 = fields[4].parse()?;
        let to_zone: u16 = fields[5].parse()?;
        let to_x: f32 = fields[6].parse()?;
        let to_y: f32 = fields[7].parse()?;
        let to_z: f32 = fields[8].parse()?;
        let scale_x: f32 = fields[9].parse()?;
        let scale_z: f32 = fields[10].parse()?;
        let rotation: f32 = fields[11].parse()?;

        out.push(ParsedLine {
            line_id,
            from_zone,
            from_pos: [from_x, from_y, from_z],
            to_zone,
            to_pos: [to_x, to_y, to_z],
            scale_x,
            scale_z,
            rotation,
        });
    }
    if out.is_empty() {
        bail!("parsed zero zonelines — schema may have changed");
    }
    Ok(out)
}
