//! Build-time scrape of the zone-id -> ROM DAT file-id mapping.
//!
//! ## Source-of-truth
//!
//! The mapping is **a formula**, not a table — it lives as a single
//! `var fileId = x < N ? x + A : x + B;` expression inside
//! `ParseD_MSG()` in FFXI-NavMesh-Builder's `Common/dat/Types/d_ms.cs`
//! (vendored at `vendor/ffxi-navmesh-builder/d_ms.cs`, pinned commit
//! recorded in the NOTICE next to it).
//!
//! The valid zone-id list comes from LSB's
//! `vendor/server/sql/zone_settings.sql` — the same set of ids the
//! server actually accepts as a "zone".
//!
//! ## Output
//!
//! Writes `$OUT_DIR/zone_dat_table.rs` containing a binary-searchable
//! `pub const ZONE_DAT_TABLE: &[(u16, u32)]` sorted by zone-id. That
//! file is `include!`d from `src/zone_dat.rs`.
//!
//! Any change to either vendored file triggers a rebuild.

use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, bail};

const D_MS_CS: &str = "../vendor/ffxi-navmesh-builder/d_ms.cs";
const ZONE_SETTINGS_SQL: &str = "../vendor/server/sql/zone_settings.sql";

fn main() -> Result<()> {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={D_MS_CS}");
    println!("cargo:rerun-if-changed={ZONE_SETTINGS_SQL}");

    let formula = parse_formula(Path::new(D_MS_CS))
        .with_context(|| format!("parsing formula from {D_MS_CS}"))?;
    let zones = parse_zone_ids(Path::new(ZONE_SETTINGS_SQL))
        .with_context(|| format!("parsing zone-ids from {ZONE_SETTINGS_SQL}"))?;

    let mut rows: Vec<(u16, u32)> = zones
        .iter()
        .copied()
        .map(|zid| (zid, formula.apply(zid)))
        .collect();
    rows.sort_by_key(|(z, _)| *z);

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").context("OUT_DIR not set")?);
    let out_path = out_dir.join("zone_dat_table.rs");

    let mut s = String::new();
    s.push_str("// AUTO-GENERATED by ffxi-dat/build.rs — do not edit by hand.\n");
    s.push_str("//\n");
    s.push_str(&format!(
        "// Source formula (vendored from {D_MS_CS}):\n//   {}\n",
        formula.description()
    ));
    s.push_str(&format!(
        "// Zone-id set:    vendored from {ZONE_SETTINGS_SQL} ({} entries).\n",
        zones.len()
    ));
    s.push_str("//\n");
    s.push_str("// License of source data: GPL-3.0 (LandSandBoat/FFXI-NavMesh-Builder)\n");
    s.push_str("//                         GPL-3.0-or-later (LandSandBoat/server)\n\n");
    s.push_str(&format!(
        "/// `(zone_id, file_id)` pairs, sorted by `zone_id` for binary search.\n"
    ));
    s.push_str("pub const ZONE_DAT_TABLE: &[(u16, u32)] = &[\n");
    for (zid, fid) in &rows {
        s.push_str(&format!("    ({zid}, {fid}),\n"));
    }
    s.push_str("];\n");

    fs::write(&out_path, &s).with_context(|| format!("writing {}", out_path.display()))?;
    println!(
        "cargo:warning=ffxi-dat: generated zone_dat_table.rs with {} zones (formula: {})",
        rows.len(),
        formula.description()
    );
    Ok(())
}

/// The closed-form expression `fileId = if zone_id < threshold { zone_id + lo_offset } else { zone_id + hi_offset }`.
#[derive(Debug, Clone, Copy)]
struct Formula {
    threshold: u32,
    lo_offset: u32,
    hi_offset: u32,
}

impl Formula {
    fn apply(&self, zone_id: u16) -> u32 {
        let z = zone_id as u32;
        if z < self.threshold {
            z + self.lo_offset
        } else {
            z + self.hi_offset
        }
    }

    fn description(&self) -> String {
        format!(
            "if zone_id < {} then zone_id + {} else zone_id + {}",
            self.threshold, self.lo_offset, self.hi_offset
        )
    }
}

/// Parse the literal expression `var fileId = x < <THR> ? x + <LO> : x + <HI>;`
/// out of `d_ms.cs`. We deliberately match the exact textual shape
/// rather than a generic C# parser — a change in shape should fail
/// loud and force a human re-check.
fn parse_formula(path: &Path) -> Result<Formula> {
    let src = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;

    // Look for: var fileId = x < <N> ? x + <A> : x + <B>;
    // (allow flexible whitespace, no other syntactic flexibility — by design)
    let needle = "var fileId = x <";
    let Some(start) = src.find(needle) else {
        bail!(
            "could not find `{}` in {} — d_ms.cs format may have changed; \
             open the file and re-derive the zone_id -> file_id formula by hand",
            needle,
            path.display()
        );
    };
    // Pull until the semicolon.
    let rest = &src[start..];
    let Some(semi) = rest.find(';') else {
        bail!("no `;` after formula in {}", path.display());
    };
    let expr = &rest[..semi];

    // Now extract the three integers in order.
    let nums: Vec<u32> = expr
        .split(|c: char| !c.is_ascii_digit())
        .filter(|s| !s.is_empty())
        .filter_map(|s| s.parse::<u32>().ok())
        .collect();
    if nums.len() != 3 {
        bail!(
            "expected exactly 3 integers in formula `{}`, found {}: {:?}",
            expr,
            nums.len(),
            nums
        );
    }
    Ok(Formula {
        threshold: nums[0],
        lo_offset: nums[1],
        hi_offset: nums[2],
    })
}

/// Pull every `INSERT INTO \`zone_settings\` VALUES (<id>, ...)` row's
/// first field as a `u16` zone-id. Skip id=0 ("unknown" demo zone).
fn parse_zone_ids(path: &Path) -> Result<Vec<u16>> {
    const PREFIX: &str = "INSERT INTO `zone_settings` VALUES (";
    let src = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let mut out = Vec::new();
    for (lineno, line) in src.lines().enumerate() {
        let Some(rest) = line.trim_start().strip_prefix(PREFIX) else {
            continue;
        };
        // First field, comma-separated.
        let Some(first_comma) = rest.find(',') else {
            bail!("zone_settings.sql line {}: no comma after id", lineno + 1);
        };
        let zid: u16 = rest[..first_comma]
            .trim()
            .parse()
            .with_context(|| format!("zone_settings.sql line {}: bad id `{}`", lineno + 1, &rest[..first_comma]))?;
        if zid == 0 {
            // Demo / unknown zone has no client-side mesh.
            continue;
        }
        out.push(zid);
    }
    if out.is_empty() {
        bail!("parsed zero rows from {} — schema may have changed", path.display());
    }
    Ok(out)
}
