use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{bail, Context, Result};
use lsb_scrape::check_scrape_count;

// Zone id -> zone MZB DAT file id. Client-lineage-wide, not build-specific:
// research/xi-tools/docs/reference/ps2_decomp_crosscheck.md "Per-zone DAT ids"
// (XiZone::OpenIndoor, map_num + 100) and
// research/xim/src/jsMain/kotlin/xim/resource/table/ZoneTables.kt
// getMainAreaResourcePath (0x64 + zoneId below 0x100, 0x147B3 + (zoneId - 0x100)
// above, i.e. zoneId + 83635).
const ZONE_DAT_HI_OFFSET: u32 = 83635;
const ZONE_DAT_FORMULA: Formula = Formula {
    threshold: 256,
    lo_offset: 100,
    hi_offset: ZONE_DAT_HI_OFFSET,
};

const ZONE_SETTINGS_SQL: &str = "../vendor/server/sql/zone_settings.sql";

/// Smallest row count each scrape can return and still plausibly have parsed
/// its source; the argument is the count the pinned vendor tree yields today
/// (kuluu-m4yk).
mod floor {
    use lsb_scrape::scrape_floor;

    pub const ZONE_SETTINGS: usize = scrape_floor(299);
}

fn main() -> Result<()> {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={ZONE_SETTINGS_SQL}");

    let formula = ZONE_DAT_FORMULA;
    let zones = parse_zone_ids(Path::new(ZONE_SETTINGS_SQL))
        .with_context(|| format!("parsing zone-ids from {ZONE_SETTINGS_SQL}"))?;
    check_scrape_count(
        "zone_settings rows",
        ZONE_SETTINGS_SQL,
        zones.len(),
        floor::ZONE_SETTINGS,
    )?;

    let mut rows: Vec<(u16, u32)> = zones
        .iter()
        .copied()
        .map(|zid| (zid, formula.apply(zid)))
        .collect();
    rows.sort_by_key(|(z, _)| *z);

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").context("OUT_DIR not set")?);
    let out_path = out_dir.join("zone_dat_table.rs");

    let mut s = String::new();
    s.push_str("// AUTO-GENERATED by ffxi-dat/build.rs — do not edit by hand.\n");
    s.push_str("//\n");
    s.push_str(&format!("// Formula:\n//   {}\n", formula.description()));
    s.push_str(&format!(
        "// Zone-id set:    vendored from {ZONE_SETTINGS_SQL} ({} entries).\n",
        zones.len()
    ));
    s.push_str("//\n");
    s.push_str(&format!(
        "pub const ZONE_DAT_THRESHOLD: u16 = {};\n",
        formula.threshold
    ));
    s.push_str(&format!(
        "pub const ZONE_DAT_LO_OFFSET: u32 = {};\n",
        formula.lo_offset
    ));
    s.push_str(&format!(
        "pub const ZONE_DAT_HI_OFFSET: u32 = {};\n",
        formula.hi_offset
    ));
    s.push_str("/// `(zone_id, file_id)` pairs, sorted by `zone_id` for binary search.\n");
    s.push_str("pub const ZONE_DAT_TABLE: &[(u16, u32)] = &[\n");
    for (zid, fid) in &rows {
        s.push_str(&format!("    ({zid}, {fid}),\n"));
    }
    s.push_str("];\n");

    fs::write(&out_path, &s).with_context(|| format!("writing {}", out_path.display()))?;
    println!(
        "ffxi-dat: generated zone_dat_table.rs with {} zones (formula: {})",
        rows.len(),
        formula.description()
    );
    Ok(())
}

#[derive(Debug, Clone, Copy)]
struct Formula {
    threshold: u16,
    lo_offset: u32,
    hi_offset: u32,
}

impl Formula {
    fn apply(&self, zone_id: u16) -> u32 {
        let z = zone_id as u32;
        if z < u32::from(self.threshold) {
            z + self.lo_offset
        } else {
            z + self.hi_offset
        }
    }

    fn description(&self) -> String {
        format!(
            "if zone_id < {} then zone_id + {} else zone_id + {}",
            self.threshold, self.lo_offset, self.hi_offset
        )
    }
}

fn parse_zone_ids(path: &Path) -> Result<Vec<u16>> {
    const PREFIX: &str = "INSERT INTO `zone_settings` VALUES (";
    let src = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let mut out = Vec::new();
    for (lineno, line) in src.lines().enumerate() {
        let Some(rest) = line.trim_start().strip_prefix(PREFIX) else {
            continue;
        };

        let Some(first_comma) = rest.find(',') else {
            bail!("zone_settings.sql line {}: no comma after id", lineno + 1);
        };
        let zid: u16 = rest[..first_comma].trim().parse().with_context(|| {
            format!(
                "zone_settings.sql line {}: bad id `{}`",
                lineno + 1,
                &rest[..first_comma]
            )
        })?;
        if zid == 0 {
            continue;
        }
        out.push(zid);
    }
    Ok(out)
}
