use std::{fs, path::PathBuf};

use anyhow::{bail, Context, Result};

const LSB_BLOWFISH_CPP: &str = "../vendor/server/src/common/blowfish.cpp";
const LSB_COMPRESS_DAT: &str = "../vendor/server/res/compress.dat";
const LSB_DECOMPRESS_DAT: &str = "../vendor/server/res/decompress.dat";
const LSB_MSG_BASIC_H: &str = "../vendor/server/src/map/enums/msg_basic.h";
const LSB_MSG_LUA: &str = "../vendor/server/scripts/enum/msg.lua";
const LSB_EFFECT_LUA: &str = "../vendor/server/scripts/enum/effect.lua";
const LSB_KEY_ITEM_LUA: &str = "../vendor/server/scripts/enum/key_item.lua";
const LSB_JOB_NAME_LUA: &str = "../vendor/server/scripts/enum/job_name.lua";
const LSB_SPELL_LIST_SQL: &str = "../vendor/server/sql/spell_list.sql";
const LSB_ABILITIES_SQL: &str = "../vendor/server/sql/abilities.sql";
const LSB_WEAPON_SKILLS_SQL: &str = "../vendor/server/sql/weapon_skills.sql";
const LSB_ITEM_BASIC_SQL: &str = "../vendor/server/sql/item_basic.sql";
const LSB_ITEM_EQUIPMENT_SQL: &str = "../vendor/server/sql/item_equipment.sql";
const LSB_ITEM_USABLE_SQL: &str = "../vendor/server/sql/item_usable.sql";
const LSB_PACKET_S2C_H: &str = "../vendor/server/src/map/enums/packet_s2c.h";
const LSB_PACKET_C2S_H: &str = "../vendor/server/src/map/enums/packet_c2s.h";
const LSB_AUTH_SESSION_H: &str = "../vendor/server/src/login/auth_session.h";
const LSB_EMOTE_H: &str = "../vendor/server/src/map/enums/emote.h";
const SUBKEY_LEN: usize = 4168;

fn main() -> Result<()> {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={LSB_BLOWFISH_CPP}");
    println!("cargo:rerun-if-changed={LSB_COMPRESS_DAT}");
    println!("cargo:rerun-if-changed={LSB_DECOMPRESS_DAT}");
    println!("cargo:rerun-if-changed={LSB_MSG_BASIC_H}");
    println!("cargo:rerun-if-changed={LSB_MSG_LUA}");
    println!("cargo:rerun-if-changed={LSB_EFFECT_LUA}");
    println!("cargo:rerun-if-changed={LSB_KEY_ITEM_LUA}");
    println!("cargo:rerun-if-changed={LSB_JOB_NAME_LUA}");
    println!("cargo:rerun-if-changed={LSB_SPELL_LIST_SQL}");
    println!("cargo:rerun-if-changed={LSB_ABILITIES_SQL}");
    println!("cargo:rerun-if-changed={LSB_WEAPON_SKILLS_SQL}");
    println!("cargo:rerun-if-changed={LSB_ITEM_BASIC_SQL}");
    println!("cargo:rerun-if-changed={LSB_ITEM_EQUIPMENT_SQL}");
    println!("cargo:rerun-if-changed={LSB_ITEM_USABLE_SQL}");
    println!("cargo:rerun-if-changed={LSB_PACKET_S2C_H}");
    println!("cargo:rerun-if-changed={LSB_PACKET_C2S_H}");
    println!("cargo:rerun-if-changed={LSB_AUTH_SESSION_H}");
    println!("cargo:rerun-if-changed={LSB_EMOTE_H}");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").context("OUT_DIR not set")?);

    let src = fs::read_to_string(LSB_BLOWFISH_CPP)
        .with_context(|| format!("reading {LSB_BLOWFISH_CPP}"))?;
    let start = src
        .find("uint8 subkey[4168]")
        .context("could not locate `uint8 subkey[4168]` in blowfish.cpp")?;
    let body_start = src[start..]
        .find('{')
        .context("could not locate opening `{` of subkey table")?
        + start
        + 1;
    let body_end = src[body_start..]
        .find('}')
        .context("could not locate closing `}` of subkey table")?
        + body_start;
    let body = &src[body_start..body_end];

    let mut bytes = Vec::with_capacity(SUBKEY_LEN);
    for tok in body.split([',', ' ', '\n', '\r', '\t']) {
        let t = tok.trim();
        if let Some(hex) = t.strip_prefix("0x").or_else(|| t.strip_prefix("0X")) {
            let b =
                u8::from_str_radix(hex, 16).with_context(|| format!("parsing hex byte `{t}`"))?;
            bytes.push(b);
        } else if !t.is_empty() {
            bail!("unexpected token in subkey table: {t:?}");
        }
    }
    if bytes.len() != SUBKEY_LEN {
        bail!(
            "extracted {} subkey bytes, expected {SUBKEY_LEN}",
            bytes.len()
        );
    }
    fs::write(out_dir.join("blowfish_subkey.bin"), &bytes)?;

    let compress =
        fs::read(LSB_COMPRESS_DAT).with_context(|| format!("reading {LSB_COMPRESS_DAT}"))?;
    let decompress =
        fs::read(LSB_DECOMPRESS_DAT).with_context(|| format!("reading {LSB_DECOMPRESS_DAT}"))?;
    if compress.len() % 4 != 0 || decompress.len() % 4 != 0 {
        bail!(
            "compress.dat ({}) / decompress.dat ({}) byte counts must be multiples of 4",
            compress.len(),
            decompress.len()
        );
    }
    fs::write(out_dir.join("compress.dat"), &compress)?;
    fs::write(out_dir.join("decompress.dat"), &decompress)?;

    let msg_src = fs::read_to_string(LSB_MSG_BASIC_H)
        .with_context(|| format!("reading {LSB_MSG_BASIC_H}"))?;
    let entries = parse_msg_basic(&msg_src)?;
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by ffxi-proto/build.rs from msg_basic.h.\n");
    out.push_str("// Do not edit by hand.\n");
    out.push_str("pub const MSG_BASIC: &[(u16, &str)] = &[\n");
    for (id, text) in &entries {
        out.push_str(&format!("    ({id}, {}),\n", rust_string_literal(text)));
    }
    out.push_str("];\n");
    fs::write(out_dir.join("msg_basic_table.rs"), &out)?;
    println!("ffxi-proto: scraped {} msg_basic entries", entries.len());

    let lua_src =
        fs::read_to_string(LSB_MSG_LUA).with_context(|| format!("reading {LSB_MSG_LUA}"))?;
    for (lua_table, out_const, out_file) in [
        ("channel", "MSG_CHANNEL", "msg_channel_table.rs"),
        ("area", "MSG_AREA", "msg_area_table.rs"),
        (
            "actionModifier",
            "MSG_ACTION_MODIFIER",
            "msg_action_modifier_table.rs",
        ),
        ("system", "MSG_SYSTEM", "msg_system_table.rs"),
    ] {
        let entries = parse_lua_table(&lua_src, lua_table)?;
        let mut out = String::new();
        out.push_str("// AUTO-GENERATED by ffxi-proto/build.rs from msg.lua.\n");
        out.push_str("// Do not edit by hand.\n");
        out.push_str(&format!("pub const {out_const}: &[(u16, &str)] = &[\n"));
        for (id, text) in &entries {
            out.push_str(&format!("    ({id}, {}),\n", rust_string_literal(text)));
        }
        out.push_str("];\n");
        fs::write(out_dir.join(out_file), &out)?;
        println!(
            "ffxi-proto: scraped {} {} entries",
            entries.len(),
            lua_table_warning_label(lua_table),
        );
    }

    let effect_src =
        fs::read_to_string(LSB_EFFECT_LUA).with_context(|| format!("reading {LSB_EFFECT_LUA}"))?;
    let effect_entries = parse_xi_ident_table(&effect_src, "xi.effect")?;
    write_u16_table(
        &out_dir.join("status_names_table.rs"),
        "STATUS_NAMES",
        LSB_EFFECT_LUA,
        &effect_entries,
    )?;
    println!(
        "ffxi-proto: scraped {} status_effect entries",
        effect_entries.len(),
    );

    let key_item_src = fs::read_to_string(LSB_KEY_ITEM_LUA)
        .with_context(|| format!("reading {LSB_KEY_ITEM_LUA}"))?;
    let key_item_entries = parse_xi_ident_table(&key_item_src, "xi.keyItem")?;
    write_u16_table(
        &out_dir.join("key_item_names_table.rs"),
        "KEY_ITEM_NAMES",
        LSB_KEY_ITEM_LUA,
        &key_item_entries,
    )?;
    println!(
        "ffxi-proto: scraped {} key_item entries",
        key_item_entries.len(),
    );

    let job_src = fs::read_to_string(LSB_JOB_NAME_LUA)
        .with_context(|| format!("reading {LSB_JOB_NAME_LUA}"))?;
    let job_entries = parse_lua_indexed_pair_table(&job_src, "xi.jobName", 3)?;
    write_u16_table(
        &out_dir.join("job_names_table.rs"),
        "JOB_NAMES",
        LSB_JOB_NAME_LUA,
        &job_entries,
    )?;
    let job_abbrevs = parse_lua_indexed_pair_table(&job_src, "xi.jobName", 1)?;
    write_u16_table(
        &out_dir.join("job_abbrevs_table.rs"),
        "JOB_ABBREVS",
        LSB_JOB_NAME_LUA,
        &job_abbrevs,
    )?;
    println!("ffxi-proto: scraped {} job_name entries", job_entries.len(),);

    let spell_src = fs::read_to_string(LSB_SPELL_LIST_SQL)
        .with_context(|| format!("reading {LSB_SPELL_LIST_SQL}"))?;
    let spell_entries = parse_sql_insert_rows(&spell_src, "spell_list", 0, 1)?;
    write_u16_table(
        &out_dir.join("spell_names_table.rs"),
        "SPELL_NAMES",
        LSB_SPELL_LIST_SQL,
        &spell_entries,
    )?;
    println!("ffxi-proto: scraped {} spell entries", spell_entries.len(),);

    let spell_skill_entries = parse_spell_skill_rows(&spell_src)?;
    write_u16_u8_table(
        &out_dir.join("spell_skill_table.rs"),
        "SPELL_MAGIC_SKILL",
        LSB_SPELL_LIST_SQL,
        &spell_skill_entries,
    )?;
    println!(
        "ffxi-proto: scraped {} spell-skill entries",
        spell_skill_entries.len(),
    );

    let spell_target_entries = parse_u16_pair_rows(&spell_src, "spell_list", 7)?;
    write_u16_u16_table(
        &out_dir.join("spell_valid_target_table.rs"),
        "SPELL_VALID_TARGET",
        LSB_SPELL_LIST_SQL,
        &spell_target_entries,
    )?;
    println!(
        "ffxi-proto: scraped {} spell validTarget entries",
        spell_target_entries.len(),
    );

    let spell_anim_entries = parse_u16_pair_rows(&spell_src, "spell_list", 14)?;
    write_u16_u16_table(
        &out_dir.join("spell_animation_table.rs"),
        "SPELL_ANIMATION",
        LSB_SPELL_LIST_SQL,
        &spell_anim_entries,
    )?;
    println!(
        "ffxi-proto: scraped {} spell animation entries",
        spell_anim_entries.len(),
    );

    let abil_src = fs::read_to_string(LSB_ABILITIES_SQL)
        .with_context(|| format!("reading {LSB_ABILITIES_SQL}"))?;
    let abil_entries = parse_sql_insert_rows(&abil_src, "abilities", 0, 1)?;
    write_u16_table(
        &out_dir.join("ability_names_table.rs"),
        "ABILITY_NAMES",
        LSB_ABILITIES_SQL,
        &abil_entries,
    )?;
    println!("ffxi-proto: scraped {} ability entries", abil_entries.len(),);

    let abil_target_entries = parse_u16_pair_rows(&abil_src, "abilities", 4)?;
    write_u16_u16_table(
        &out_dir.join("ability_valid_target_table.rs"),
        "ABILITY_VALID_TARGET",
        LSB_ABILITIES_SQL,
        &abil_target_entries,
    )?;
    println!(
        "ffxi-proto: scraped {} ability validTarget entries",
        abil_target_entries.len(),
    );

    let abil_recast_entries = parse_u16_pair_rows(&abil_src, "abilities", 6)?;
    write_u16_u16_table(
        &out_dir.join("ability_recast_id_table.rs"),
        "ABILITY_RECAST_ID",
        LSB_ABILITIES_SQL,
        &abil_recast_entries,
    )?;
    println!(
        "ffxi-proto: scraped {} ability recastId entries",
        abil_recast_entries.len(),
    );

    let abil_anim_entries = parse_u16_pair_rows(&abil_src, "abilities", 9)?;
    write_u16_u16_table(
        &out_dir.join("ability_animation_table.rs"),
        "ABILITY_ANIMATION",
        LSB_ABILITIES_SQL,
        &abil_anim_entries,
    )?;
    println!(
        "ffxi-proto: scraped {} ability animation entries",
        abil_anim_entries.len(),
    );

    let ws_src = fs::read_to_string(LSB_WEAPON_SKILLS_SQL)
        .with_context(|| format!("reading {LSB_WEAPON_SKILLS_SQL}"))?;
    let ws_anim_entries = parse_u16_pair_rows(&ws_src, "weapon_skills", 6)?;
    write_u16_u16_table(
        &out_dir.join("weapon_skill_animation_table.rs"),
        "WEAPON_SKILL_ANIMATION",
        LSB_WEAPON_SKILLS_SQL,
        &ws_anim_entries,
    )?;
    println!(
        "ffxi-proto: scraped {} weapon-skill animation entries",
        ws_anim_entries.len(),
    );

    let item_src = fs::read_to_string(LSB_ITEM_BASIC_SQL)
        .with_context(|| format!("reading {LSB_ITEM_BASIC_SQL}"))?;
    let item_entries = parse_sql_insert_rows(&item_src, "item_basic", 0, 2)?;
    write_u16_table(
        &out_dir.join("item_names_table.rs"),
        "ITEM_NAMES",
        LSB_ITEM_BASIC_SQL,
        &item_entries,
    )?;
    println!("ffxi-proto: scraped {} item entries", item_entries.len(),);

    let equip_src = fs::read_to_string(LSB_ITEM_EQUIPMENT_SQL)
        .with_context(|| format!("reading {LSB_ITEM_EQUIPMENT_SQL}"))?;
    let equip_entries = parse_sql_equip_rows(&equip_src)?;
    write_equip_info_table(&out_dir.join("equip_info_table.rs"), &equip_entries)?;
    println!(
        "ffxi-proto: scraped {} equip_info entries",
        equip_entries.len(),
    );

    let usable_src = fs::read_to_string(LSB_ITEM_USABLE_SQL)
        .with_context(|| format!("reading {LSB_ITEM_USABLE_SQL}"))?;
    let usable_entries = parse_sql_usable_rows(&usable_src)?;
    write_item_usable_table(&out_dir.join("item_usable_table.rs"), &usable_entries)?;
    println!(
        "cargo:warning=ffxi-proto: scraped {} item_usable entries",
        usable_entries.len(),
    );

    let pkt_s2c_src = fs::read_to_string(LSB_PACKET_S2C_H)
        .with_context(|| format!("reading {LSB_PACKET_S2C_H}"))?;
    let s2c_names = parse_packet_enum(&pkt_s2c_src, "GP_SERV_COMMAND_")?;
    write_u16_table(
        &out_dir.join("packet_names_s2c_table.rs"),
        "PACKET_NAMES_S2C",
        LSB_PACKET_S2C_H,
        &s2c_names,
    )?;
    println!("ffxi-proto: scraped {} s2c packet names", s2c_names.len(),);

    let pkt_c2s_src = fs::read_to_string(LSB_PACKET_C2S_H)
        .with_context(|| format!("reading {LSB_PACKET_C2S_H}"))?;
    let c2s_names = parse_packet_enum(&pkt_c2s_src, "GP_CLI_COMMAND_")?;
    write_u16_table(
        &out_dir.join("packet_names_c2s_table.rs"),
        "PACKET_NAMES_C2S",
        LSB_PACKET_C2S_H,
        &c2s_names,
    )?;
    println!("ffxi-proto: scraped {} c2s packet names", c2s_names.len(),);

    let emote_src =
        fs::read_to_string(LSB_EMOTE_H).with_context(|| format!("reading {LSB_EMOTE_H}"))?;
    let emote_entries = parse_cpp_enum_class(&emote_src, "Emote")?;
    for (id, name) in &emote_entries {
        if *id > u8::MAX as u32 {
            bail!("Emote id {id} ({name:?}) overflows u8 — emote.h widened its enum?");
        }
    }
    let mut out = String::new();
    out.push_str(&format!(
        "// AUTO-GENERATED by ffxi-proto/build.rs from {LSB_EMOTE_H}.\n"
    ));
    out.push_str("// Do not edit by hand.\n");
    out.push_str("pub const EMOTES: &[(u8, &str)] = &[\n");
    for (id, name) in &emote_entries {
        out.push_str(&format!("    ({id}, {}),\n", rust_string_literal(name)));
    }
    out.push_str("];\n");
    fs::write(out_dir.join("emote_table.rs"), &out)?;
    println!("ffxi-proto: scraped {} emote entries", emote_entries.len());

    let auth_session_src = fs::read_to_string(LSB_AUTH_SESSION_H)
        .with_context(|| format!("reading {LSB_AUTH_SESSION_H}"))?;
    let xiloader_version = parse_supported_xiloader_version(&auth_session_src)?;
    let out = format!(
        "// AUTO-GENERATED by ffxi-proto/build.rs from {LSB_AUTH_SESSION_H}.\n\
         // Do not edit by hand.\n\
         pub const SUPPORTED_XILOADER_VERSION: [u8; 3] = [{}, {}, {}];\n",
        xiloader_version[0], xiloader_version[1], xiloader_version[2],
    );
    fs::write(out_dir.join("xiloader_version_table.rs"), &out)?;
    println!(
        "ffxi-proto: scraped SupportedXiloaderVersion {}.{}.{}",
        xiloader_version[0], xiloader_version[1], xiloader_version[2],
    );

    Ok(())
}

fn parse_supported_xiloader_version(src: &str) -> Result<[u8; 3]> {
    let start = src
        .find("SupportedXiloaderVersion")
        .context("could not locate `SupportedXiloaderVersion` in auth_session.h")?;
    let open = src[start..]
        .find('{')
        .context("could not locate opening `{` of SupportedXiloaderVersion")?
        + start
        + 1;
    let close = src[open..]
        .find('}')
        .context("could not locate closing `}` of SupportedXiloaderVersion")?
        + open;
    let mut parts = src[open..close].split(',').map(str::trim);
    let mut version = [0u8; 3];
    for slot in &mut version {
        let part = parts
            .next()
            .context("SupportedXiloaderVersion has fewer than 3 components")?;
        *slot = part
            .parse::<u8>()
            .with_context(|| format!("SupportedXiloaderVersion component {part:?} is not a u8"))?;
    }
    if parts.next().is_some() {
        bail!("SupportedXiloaderVersion has more than 3 components");
    }
    Ok(version)
}

fn parse_cpp_enum_class(src: &str, enum_name: &str) -> Result<Vec<(u32, String)>> {
    let needle = format!("enum class {enum_name}");
    let header = src
        .find(&needle)
        .with_context(|| format!("could not locate `{needle}` in source"))?;
    let body_start = src[header..]
        .find('{')
        .with_context(|| format!("no opening `{{` after `{needle}`"))?
        + header
        + 1;
    let body_end = src[body_start..]
        .find('}')
        .with_context(|| format!("no closing `}}` after `{needle}`"))?
        + body_start;

    let mut out = Vec::new();
    let mut seen = std::collections::HashSet::new();
    for line in src[body_start..body_end].lines() {
        let line = line.trim();
        let Some(eq) = line.find('=') else { continue };
        let ident = line[..eq].trim();
        if ident.is_empty() || !ident.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            continue;
        }
        let value = line[eq + 1..].split([',', '/']).next().unwrap_or("").trim();
        let Some(id) = parse_int_lit(value) else {
            continue;
        };
        if seen.insert(id) {
            out.push((id as u32, ident.to_string()));
        }
    }
    if out.is_empty() {
        bail!("parsed zero entries for `enum class {enum_name}` — header format may have changed");
    }
    out.sort_by_key(|(id, _)| *id);
    Ok(out)
}

fn parse_packet_enum(src: &str, prefix: &str) -> Result<Vec<(u32, String)>> {
    let mut out = Vec::new();
    let mut seen = std::collections::HashSet::new();
    for line in src.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix(prefix) else {
            continue;
        };
        let Some(eq) = rest.find('=') else { continue };
        let name = rest[..eq].trim();
        if name.is_empty() || !name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            continue;
        }
        let num_str = rest[eq + 1..].trim().trim_end_matches(',').trim();
        let Some(id) = parse_int_lit(num_str) else {
            continue;
        };
        if seen.insert(id) {
            out.push((id as u32, name.to_string()));
        }
    }
    if out.is_empty() {
        bail!("parsed zero `{prefix}*` packet ids — packet enum format may have changed");
    }
    Ok(out)
}

#[derive(Debug, Clone, Copy)]
struct EquipRow {
    item_id: u16,
    level: u8,
    jobs_mask: u32,
    slot_mask: u16,
}

fn parse_sql_equip_rows(src: &str) -> Result<Vec<EquipRow>> {
    let needle = "INSERT INTO `item_equipment` VALUES ";
    let mut out = Vec::new();
    for line in src.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix(needle) else {
            continue;
        };
        let mut cursor = rest;
        while let Some(open) = cursor.find('(') {
            cursor = &cursor[open + 1..];
            let Some((tuple, after)) = split_sql_tuple(cursor) else {
                break;
            };
            cursor = after;
            let fields = split_sql_fields(tuple);
            let Some(row) = parse_equip_row(&fields) else {
                continue;
            };
            out.push(row);
        }
    }
    if out.is_empty() {
        bail!(
            "parsed zero rows from `INSERT INTO item_equipment` — \
             SQL format may have changed"
        );
    }

    out.sort_by_key(|e| e.item_id);
    out.dedup_by_key(|e| e.item_id);
    Ok(out)
}

fn parse_equip_row(fields: &[&str]) -> Option<EquipRow> {
    let item_id: u16 = fields.first()?.trim().parse().ok()?;

    let level: u8 = fields.get(2)?.trim().parse::<u16>().ok()?.min(255) as u8;
    let jobs_mask: u32 = fields.get(4)?.trim().parse().ok()?;
    let slot_mask: u16 = fields.get(8)?.trim().parse().ok()?;
    Some(EquipRow {
        item_id,
        level,
        jobs_mask,
        slot_mask,
    })
}

#[derive(Debug, Clone, Copy)]
struct UsableRow {
    item_id: u16,
    valid_targets: u16,
    max_charges: u8,
}

/// Scrapes LSB `item_usable` (itemId, name, validTargets, activation,
/// animation, animationTime, maxCharges, useDelay, reuseDelay, aoe) — the
/// table 0x037 item-use consults for whether an item can fire at all.
fn parse_sql_usable_rows(src: &str) -> Result<Vec<UsableRow>> {
    let needle = "INSERT INTO `item_usable` VALUES ";
    let mut out = Vec::new();
    for line in src.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix(needle) else {
            continue;
        };
        let mut cursor = rest;
        while let Some(open) = cursor.find('(') {
            cursor = &cursor[open + 1..];
            let Some((tuple, after)) = split_sql_tuple(cursor) else {
                break;
            };
            cursor = after;
            let fields = split_sql_fields(tuple);
            let Some(row) = parse_usable_row(&fields) else {
                continue;
            };
            out.push(row);
        }
    }
    if out.is_empty() {
        bail!(
            "parsed zero rows from `INSERT INTO item_usable` — \
             SQL format may have changed"
        );
    }

    out.sort_by_key(|e| e.item_id);
    out.dedup_by_key(|e| e.item_id);
    Ok(out)
}

fn parse_usable_row(fields: &[&str]) -> Option<UsableRow> {
    let item_id: u16 = fields.first()?.trim().parse().ok()?;
    let valid_targets: u16 = fields.get(2)?.trim().parse().ok()?;
    let max_charges: u8 = fields.get(6)?.trim().parse::<u16>().ok()?.min(255) as u8;
    Some(UsableRow {
        item_id,
        valid_targets,
        max_charges,
    })
}

fn write_item_usable_table(out_path: &PathBuf, entries: &[UsableRow]) -> Result<()> {
    use std::io::Write;
    let mut f =
        fs::File::create(out_path).with_context(|| format!("creating {}", out_path.display()))?;
    writeln!(
        f,
        "// Auto-generated from {LSB_ITEM_USABLE_SQL} by build.rs — do not edit."
    )?;
    writeln!(f, "pub static ITEM_USABLE: &[(u16, u16, u8)] = &[")?;
    for row in entries {
        writeln!(
            f,
            "    ({}, {}, {}),",
            row.item_id, row.valid_targets, row.max_charges
        )?;
    }
    writeln!(f, "];")?;
    Ok(())
}

fn write_equip_info_table(out_path: &PathBuf, entries: &[EquipRow]) -> Result<()> {
    use std::io::Write;
    let mut f =
        fs::File::create(out_path).with_context(|| format!("creating {}", out_path.display()))?;
    writeln!(
        f,
        "// Auto-generated from {LSB_ITEM_EQUIPMENT_SQL} by build.rs — do not edit."
    )?;
    writeln!(f, "pub static EQUIP_INFO: &[(u16, u8, u32, u16)] = &[")?;
    for row in entries {
        writeln!(
            f,
            "    ({}, {}, {}, {}),",
            row.item_id, row.level, row.jobs_mask, row.slot_mask
        )?;
    }
    writeln!(f, "];")?;
    Ok(())
}

fn lua_table_warning_label(table: &str) -> &'static str {
    match table {
        "channel" => "msg_channel",
        "area" => "msg_area",
        "actionModifier" => "msg_action_modifier",
        "system" => "msg_system",
        _ => "msg_<unknown>",
    }
}

fn parse_lua_table(src: &str, table: &str) -> Result<Vec<(u16, String)>> {
    let needle = format!("xi.msg.{table} =");
    let header = src
        .find(&needle)
        .with_context(|| format!("could not locate `{needle}` in msg.lua"))?;

    let body_start = src[header..]
        .find('{')
        .with_context(|| format!("no opening `{{` after `{needle}`"))?
        + header
        + 1;
    let body_end = src[body_start..]
        .find('}')
        .with_context(|| format!("no closing `}}` after `{needle}`"))?
        + body_start;
    let body = &src[body_start..body_end];

    let mut out = Vec::new();
    let mut seen = std::collections::HashSet::new();
    for line in body.lines() {
        let line = line.trim();
        let Some(eq) = line.find('=') else { continue };
        let ident = line[..eq].trim();
        if ident.is_empty()
            || !ident
                .chars()
                .next()
                .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        {
            continue;
        }
        if !ident.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            continue;
        }

        let tail = &line[eq + 1..];
        let Some(comma) = tail.find(',') else {
            continue;
        };
        let num_str = tail[..comma].trim();
        let id: u16 = parse_int_lit(num_str).unwrap_or(continue_marker());
        if id == continue_marker() {
            continue;
        }
        let after_comma = &tail[comma + 1..];
        let Some(slash) = after_comma.find("--") else {
            continue;
        };
        let comment = after_comma[slash + 2..].trim().to_string();
        if comment.is_empty() || is_non_message_annotation(&comment) {
            continue;
        }
        if seen.insert(id) {
            out.push((id, comment));
        }
    }
    if out.is_empty() {
        bail!("parsed zero entries for xi.msg.{table} — msg.lua format may have changed");
    }
    Ok(out)
}

fn continue_marker() -> u16 {
    u16::MAX
}

fn parse_int_lit(s: &str) -> Option<u16> {
    if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        u16::from_str_radix(hex, 16).ok()
    } else {
        s.parse().ok()
    }
}

fn parse_msg_basic(src: &str) -> Result<Vec<(u16, String)>> {
    let mut out = Vec::new();
    for line in src.lines() {
        let line = line.trim();

        let Some(eq) = line.find('=') else { continue };

        let Some(comma) = line[eq..].find(',') else {
            continue;
        };
        let comma = eq + comma;

        let ident = line[..eq].trim();
        if ident.is_empty()
            || !ident
                .chars()
                .next()
                .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        {
            continue;
        }
        if !ident.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            continue;
        }

        let num_str = line[eq + 1..comma].trim();
        let id: u16 = match num_str.parse() {
            Ok(n) => n,
            Err(_) => continue,
        };

        let tail = &line[comma + 1..];
        let Some(slash) = tail.find("//") else {
            continue;
        };
        let mut comment = tail[slash + 2..].trim().to_string();

        if let Some(stripped) = comment.strip_suffix("*/") {
            comment = stripped.trim_end().to_string();
        }
        if is_non_message_annotation(&comment) {
            continue;
        }
        if comment.is_empty() {
            continue;
        }
        out.push((id, comment));
    }
    if out.is_empty() {
        bail!("parsed zero msg_basic entries — header format may have changed");
    }
    Ok(out)
}

fn is_non_message_annotation(comment: &str) -> bool {
    let low = comment.to_ascii_lowercase();

    low.contains("display nothing")
        || low.contains("does not print")
        || low.contains("does not work")
        || low.contains("does nothing")
        || low.starts_with("(assumed")
        || low.starts_with("assumed")
        || low.starts_with("todo")
        || low.starts_with("unused")
}

fn rust_string_literal(s: &str) -> String {
    if !s.contains('"') && !s.contains('\\') {
        format!("\"{s}\"")
    } else {
        let mut esc = String::with_capacity(s.len() + 2);
        esc.push('"');
        for c in s.chars() {
            match c {
                '"' => esc.push_str("\\\""),
                '\\' => esc.push_str("\\\\"),
                _ => esc.push(c),
            }
        }
        esc.push('"');
        esc
    }
}

fn write_u16_table(
    out_path: &std::path::Path,
    const_name: &str,
    source_path: &str,
    entries: &[(u32, String)],
) -> Result<()> {
    let mut entries: Vec<(u32, String)> = entries.to_vec();
    entries.sort_by_key(|(id, _)| *id);
    entries.dedup_by_key(|(id, _)| *id);

    for (id, name) in &entries {
        if *id > u16::MAX as u32 {
            bail!("entry id {id} ({name:?}) overflows u16 — table needs widening");
        }
    }
    let mut out = String::new();
    out.push_str(&format!(
        "// AUTO-GENERATED by ffxi-proto/build.rs from {source_path}.\n"
    ));
    out.push_str("// Do not edit by hand.\n");
    out.push_str(&format!("pub const {const_name}: &[(u16, &str)] = &[\n"));
    for (id, text) in &entries {
        out.push_str(&format!("    ({id}, {}),\n", rust_string_literal(text)));
    }
    out.push_str("];\n");
    fs::write(out_path, &out)?;
    Ok(())
}

fn parse_xi_ident_table(src: &str, needle_prefix: &str) -> Result<Vec<(u32, String)>> {
    let needle = format!("{needle_prefix} =");
    let header = src
        .find(&needle)
        .with_context(|| format!("could not locate `{needle}` in source"))?;
    let body_start = src[header..]
        .find('{')
        .with_context(|| format!("no opening `{{` after `{needle}`"))?
        + header
        + 1;

    let body_end = src[body_start..]
        .find('}')
        .with_context(|| format!("no closing `}}` after `{needle}`"))?
        + body_start;
    let body = &src[body_start..body_end];

    let mut out = Vec::new();
    let mut seen = std::collections::HashSet::new();
    for line in body.lines() {
        let line = line.trim();
        let Some(eq) = line.find('=') else { continue };
        let ident = line[..eq].trim();
        if ident.is_empty()
            || !ident
                .chars()
                .next()
                .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        {
            continue;
        }
        if !ident.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            continue;
        }
        let tail = line[eq + 1..].trim_start();
        let num_str: String = tail
            .chars()
            .take_while(|c| c.is_ascii_digit() || *c == '-')
            .collect();
        let Ok(id) = num_str.parse::<u32>() else {
            continue;
        };
        let pretty = prettify_snake_case(ident);
        if seen.insert(id) {
            out.push((id, pretty));
        }
    }
    if out.is_empty() {
        bail!("parsed zero entries for `{needle_prefix}` — source format may have changed");
    }
    Ok(out)
}

// `field` selects which quoted string in each `[id] = { 'ABBR', 'Full Name' }`
// row to keep: 1 = abbreviation, 3 = display name (split-by-`'` part index).
fn parse_lua_indexed_pair_table(
    src: &str,
    needle_prefix: &str,
    field: usize,
) -> Result<Vec<(u32, String)>> {
    let needle = format!("{needle_prefix} =");
    let header = src
        .find(&needle)
        .with_context(|| format!("could not locate `{needle}` in source"))?;
    let body_start = src[header..]
        .find('{')
        .with_context(|| format!("no opening `{{` after `{needle}`"))?
        + header
        + 1;
    let body = &src[body_start..];

    let mut out = Vec::new();
    let mut seen = std::collections::HashSet::new();
    for line in body.lines() {
        let line = line.trim();

        let Some(open) = line.find('[') else { continue };
        let Some(close) = line[open + 1..].find(']') else {
            continue;
        };
        let id_str = line[open + 1..open + 1 + close].trim();
        let Ok(id) = id_str.parse::<u32>() else {
            continue;
        };

        let rest = &line[open + 1 + close..];
        let parts: Vec<&str> = rest.split('\'').collect();

        if parts.len() <= field {
            continue;
        }
        let display = parts[field].trim();
        if display.is_empty() {
            continue;
        }
        if seen.insert(id) {
            out.push((id, display.to_string()));
        }
    }
    if out.is_empty() {
        bail!("parsed zero entries for `{needle_prefix}` — source format may have changed");
    }
    Ok(out)
}

fn parse_sql_insert_rows(
    src: &str,
    table: &str,
    id_field: usize,
    name_field: usize,
) -> Result<Vec<(u32, String)>> {
    let needle = format!("INSERT INTO `{table}` VALUES ");
    let mut out = Vec::new();
    for line in src.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix(needle.as_str()) else {
            continue;
        };

        let mut cursor = rest;
        while let Some(open) = cursor.find('(') {
            cursor = &cursor[open + 1..];
            let Some((tuple, after)) = split_sql_tuple(cursor) else {
                break;
            };
            cursor = after;
            let fields = split_sql_fields(tuple);
            let id_str = fields.get(id_field).map(|s| s.trim()).unwrap_or("");
            let name_raw = fields.get(name_field).map(|s| s.trim()).unwrap_or("");
            let Ok(id) = id_str.parse::<u32>() else {
                continue;
            };
            let Some(name) = strip_sql_string(name_raw) else {
                continue;
            };

            if name.is_empty()
                || name.chars().all(|c| c == '_')
                || !name.chars().next().is_some_and(|c| c.is_ascii_alphabetic())
            {
                continue;
            }
            out.push((id, prettify_snake_case(&name)));
        }
    }
    if out.is_empty() {
        bail!("parsed zero rows from `INSERT INTO {table}` — SQL format may have changed");
    }
    Ok(out)
}

fn parse_u16_pair_rows(src: &str, table: &str, value_field: usize) -> Result<Vec<(u16, u16)>> {
    let needle = format!("INSERT INTO `{table}` VALUES ");
    let mut out = Vec::new();
    for line in src.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix(needle.as_str()) else {
            continue;
        };
        let mut cursor = rest;
        while let Some(open) = cursor.find('(') {
            cursor = &cursor[open + 1..];
            let Some((tuple, after)) = split_sql_tuple(cursor) else {
                break;
            };
            cursor = after;
            let fields = split_sql_fields(tuple);
            let Some(Ok(id)) = fields.first().map(|s| s.trim().parse::<u16>()) else {
                continue;
            };
            let value = fields
                .get(value_field)
                .and_then(|s| s.trim().parse::<u16>().ok())
                .unwrap_or(0);
            out.push((id, value));
        }
    }
    if out.is_empty() {
        bail!("parsed zero rows from `INSERT INTO {table}` — SQL format may have changed");
    }
    Ok(out)
}

fn parse_spell_skill_rows(src: &str) -> Result<Vec<(u16, u8)>> {
    let mut skill_consts: std::collections::HashMap<&str, u8> = std::collections::HashMap::new();
    for line in src.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("SET ") else {
            continue;
        };
        let Some((name, val)) = rest.split_once('=') else {
            continue;
        };
        let name = name.trim();
        if !name.starts_with("@SKILL_") {
            continue;
        }
        let val = val.trim().trim_end_matches(';').trim();
        if let Ok(n) = val.parse::<u8>() {
            skill_consts.insert(name, n);
        }
    }

    let needle = "INSERT INTO `spell_list` VALUES ";
    let mut out = Vec::new();
    for line in src.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix(needle) else {
            continue;
        };
        let mut cursor = rest;
        while let Some(open) = cursor.find('(') {
            cursor = &cursor[open + 1..];
            let Some((tuple, after)) = split_sql_tuple(cursor) else {
                break;
            };
            cursor = after;
            let fields = split_sql_fields(tuple);
            let Some(id_str) = fields.first().map(|s| s.trim()) else {
                continue;
            };
            let Ok(id) = id_str.parse::<u16>() else {
                continue;
            };
            let skill_raw = fields.get(8).map(|s| s.trim()).unwrap_or("");
            let skill = skill_consts
                .get(skill_raw)
                .copied()
                .or_else(|| skill_raw.parse::<u8>().ok());
            let Some(skill) = skill else { continue };
            if skill == 0 {
                continue;
            }
            out.push((id, skill));
        }
    }
    if out.is_empty() {
        bail!("parsed zero spell-skill rows — spell_list.sql format may have changed");
    }
    Ok(out)
}

fn write_u16_u8_table(
    out_path: &std::path::Path,
    const_name: &str,
    source_path: &str,
    entries: &[(u16, u8)],
) -> Result<()> {
    let mut entries = entries.to_vec();
    entries.sort_by_key(|(id, _)| *id);
    entries.dedup_by_key(|(id, _)| *id);

    let mut out = String::new();
    out.push_str(&format!(
        "// AUTO-GENERATED by ffxi-proto/build.rs from {source_path}.\n"
    ));
    out.push_str("// Do not edit by hand.\n");
    out.push_str(&format!("pub const {const_name}: &[(u16, u8)] = &[\n"));
    for (id, skill) in &entries {
        out.push_str(&format!("    ({id}, {skill}),\n"));
    }
    out.push_str("];\n");
    fs::write(out_path, &out)?;
    Ok(())
}

fn write_u16_u16_table(
    out_path: &std::path::Path,
    const_name: &str,
    source_path: &str,
    entries: &[(u16, u16)],
) -> Result<()> {
    let mut entries = entries.to_vec();
    entries.sort_by_key(|(id, _)| *id);
    entries.dedup_by_key(|(id, _)| *id);

    let mut out = String::new();
    out.push_str(&format!(
        "// AUTO-GENERATED by ffxi-proto/build.rs from {source_path}.\n"
    ));
    out.push_str("// Do not edit by hand.\n");
    out.push_str(&format!("pub const {const_name}: &[(u16, u16)] = &[\n"));
    for (id, value) in &entries {
        out.push_str(&format!("    ({id}, {value}),\n"));
    }
    out.push_str("];\n");
    fs::write(out_path, &out)?;
    Ok(())
}

fn split_sql_tuple(s: &str) -> Option<(&str, &str)> {
    let bytes = s.as_bytes();
    let mut i = 0;
    let mut in_string = false;
    while i < bytes.len() {
        let c = bytes[i];
        if in_string {
            if c == b'\'' {
                if i + 1 < bytes.len() && bytes[i + 1] == b'\'' {
                    i += 2;
                    continue;
                }
                in_string = false;
            }
            i += 1;
        } else {
            if c == b'\'' {
                in_string = true;
                i += 1;
                continue;
            }
            if c == b')' {
                return Some((&s[..i], &s[i + 1..]));
            }
            i += 1;
        }
    }
    None
}

fn split_sql_fields(tuple: &str) -> Vec<&str> {
    let bytes = tuple.as_bytes();
    let mut fields = Vec::new();
    let mut start = 0usize;
    let mut i = 0usize;
    let mut in_string = false;
    while i < bytes.len() {
        let c = bytes[i];
        if in_string {
            if c == b'\'' {
                if i + 1 < bytes.len() && bytes[i + 1] == b'\'' {
                    i += 2;
                    continue;
                }
                in_string = false;
            }
            i += 1;
        } else if c == b'\'' {
            in_string = true;
            i += 1;
        } else if c == b',' {
            fields.push(&tuple[start..i]);
            start = i + 1;
            i += 1;
        } else {
            i += 1;
        }
    }
    fields.push(&tuple[start..]);
    fields
}

fn strip_sql_string(field: &str) -> Option<String> {
    let f = field.trim();
    let stripped = f.strip_prefix('\'').and_then(|s| s.strip_suffix('\''))?;
    Some(stripped.replace("''", "'"))
}

fn prettify_snake_case(s: &str) -> String {
    const ROMAN: &[&str] = &[
        "i", "ii", "iii", "iv", "v", "vi", "vii", "viii", "ix", "x", "xi", "xii", "xiii", "xiv",
        "xv",
    ];
    const CONNECTORS: &[&str] = &["of", "the", "a", "an", "in", "on", "and", "to"];
    let words: Vec<&str> = s.split('_').filter(|w| !w.is_empty()).collect();
    let mut out = String::with_capacity(s.len() + words.len());
    for (idx, word) in words.iter().enumerate() {
        if idx > 0 {
            out.push(' ');
        }
        let lower = word.to_ascii_lowercase();
        if ROMAN.iter().any(|r| *r == lower) {
            out.push_str(&lower.to_ascii_uppercase());
        } else if idx > 0 && CONNECTORS.iter().any(|c| *c == lower) {
            out.push_str(&lower);
        } else {
            let mut chars = lower.chars();
            if let Some(first) = chars.next() {
                out.push(first.to_ascii_uppercase());
                out.push_str(chars.as_str());
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prettify_handles_roman_numerals_and_connectors() {
        assert_eq!(prettify_snake_case("cure"), "Cure");
        assert_eq!(prettify_snake_case("cure_iv"), "Cure IV");
        assert_eq!(prettify_snake_case("cure_vi"), "Cure VI");
        assert_eq!(
            prettify_snake_case("pile_of_chocobo_bedding"),
            "Pile of Chocobo Bedding"
        );
        assert_eq!(prettify_snake_case("BLAZE_SPIKES"), "Blaze Spikes");
        assert_eq!(prettify_snake_case("mighty_strikes"), "Mighty Strikes");
    }

    #[test]
    fn sql_tuple_handles_escaped_quotes() {
        let (body, after) = split_sql_tuple("1,'it''s',2);extra").unwrap();
        assert_eq!(body, "1,'it''s',2");
        assert_eq!(after, ";extra");
        let fields = split_sql_fields(body);
        assert_eq!(fields.len(), 3);
        assert_eq!(strip_sql_string(fields[1]).unwrap(), "it's");
    }
}
