//! Extract the FFXI Blowfish subkey table from the LSB C++ source, copy
//! the FFXI custom-zlib lookup tables (`compress.dat`/`decompress.dat`) from
//! the LSB resources, and scrape the `msg_basic.h` enum into a static
//! `(u16, &str)` table — keeping the Rust port in sync with upstream
//! byte-for-byte and string-for-string.

use std::{fs, path::PathBuf};

use anyhow::{Context, Result, bail};

const LSB_BLOWFISH_CPP: &str = "../vendor/server/src/common/blowfish.cpp";
const LSB_COMPRESS_DAT: &str = "../vendor/server/res/compress.dat";
const LSB_DECOMPRESS_DAT: &str = "../vendor/server/res/decompress.dat";
const LSB_MSG_BASIC_H: &str = "../vendor/server/src/map/enums/msg_basic.h";
const LSB_MSG_LUA: &str = "../vendor/server/scripts/enum/msg.lua";
const SUBKEY_LEN: usize = 4168;

fn main() -> Result<()> {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={LSB_BLOWFISH_CPP}");
    println!("cargo:rerun-if-changed={LSB_COMPRESS_DAT}");
    println!("cargo:rerun-if-changed={LSB_DECOMPRESS_DAT}");
    println!("cargo:rerun-if-changed={LSB_MSG_BASIC_H}");
    println!("cargo:rerun-if-changed={LSB_MSG_LUA}");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").context("OUT_DIR not set")?);

    // Blowfish subkey table.
    let src = fs::read_to_string(LSB_BLOWFISH_CPP)
        .with_context(|| format!("reading {LSB_BLOWFISH_CPP}"))?;
    let start = src
        .find("uint8 subkey[4168]")
        .context("could not locate `uint8 subkey[4168]` in blowfish.cpp")?;
    let body_start = src[start..]
        .find('{')
        .context("could not locate opening `{` of subkey table")?
        + start
        + 1;
    let body_end = src[body_start..]
        .find('}')
        .context("could not locate closing `}` of subkey table")?
        + body_start;
    let body = &src[body_start..body_end];

    let mut bytes = Vec::with_capacity(SUBKEY_LEN);
    for tok in body.split([',', ' ', '\n', '\r', '\t']) {
        let t = tok.trim();
        if let Some(hex) = t.strip_prefix("0x").or_else(|| t.strip_prefix("0X")) {
            let b = u8::from_str_radix(hex, 16)
                .with_context(|| format!("parsing hex byte `{t}`"))?;
            bytes.push(b);
        } else if !t.is_empty() {
            bail!("unexpected token in subkey table: {t:?}");
        }
    }
    if bytes.len() != SUBKEY_LEN {
        bail!(
            "extracted {} subkey bytes, expected {SUBKEY_LEN}",
            bytes.len()
        );
    }
    fs::write(out_dir.join("blowfish_subkey.bin"), &bytes)?;

    // FFXI custom-zlib tables: copy verbatim.
    let compress = fs::read(LSB_COMPRESS_DAT)
        .with_context(|| format!("reading {LSB_COMPRESS_DAT}"))?;
    let decompress = fs::read(LSB_DECOMPRESS_DAT)
        .with_context(|| format!("reading {LSB_DECOMPRESS_DAT}"))?;
    if compress.len() % 4 != 0 || decompress.len() % 4 != 0 {
        bail!(
            "compress.dat ({}) / decompress.dat ({}) byte counts must be multiples of 4",
            compress.len(),
            decompress.len()
        );
    }
    fs::write(out_dir.join("compress.dat"), &compress)?;
    fs::write(out_dir.join("decompress.dat"), &decompress)?;

    // msg_basic.h → (u16, &str) table. Each entry is a single line of the form
    //   Identifier = Number,  // English message text
    // Lines without a trailing comment, or whose comment is a non-message
    // annotation ("Display nothing", "Does not print", ...), are skipped.
    let msg_src = fs::read_to_string(LSB_MSG_BASIC_H)
        .with_context(|| format!("reading {LSB_MSG_BASIC_H}"))?;
    let entries = parse_msg_basic(&msg_src)?;
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by ffxi-proto/build.rs from msg_basic.h.\n");
    out.push_str("// Do not edit by hand.\n");
    out.push_str("pub const MSG_BASIC: &[(u16, &str)] = &[\n");
    for (id, text) in &entries {
        out.push_str(&format!("    ({id}, {}),\n", rust_string_literal(text)));
    }
    out.push_str("];\n");
    fs::write(out_dir.join("msg_basic_table.rs"), &out)?;
    println!("cargo:warning=ffxi-proto: scraped {} msg_basic entries", entries.len());

    // msg.lua → one (u16, &str) table per `xi.msg.<table>`. Each line in
    // a table body is `IDENT = NUM, -- text`. Same skip rules as the
    // msg_basic header. We deliberately skip `xi.msg.basic` here — the
    // canonical source for combat text is `msg_basic.h` (already scraped
    // above); the lua mirror is a partial subset and would only confuse
    // lookups by overlapping ids.
    let lua_src = fs::read_to_string(LSB_MSG_LUA)
        .with_context(|| format!("reading {LSB_MSG_LUA}"))?;
    for (lua_table, out_const, out_file) in [
        ("channel", "MSG_CHANNEL", "msg_channel_table.rs"),
        ("area", "MSG_AREA", "msg_area_table.rs"),
        ("actionModifier", "MSG_ACTION_MODIFIER", "msg_action_modifier_table.rs"),
        ("system", "MSG_SYSTEM", "msg_system_table.rs"),
    ] {
        let entries = parse_lua_table(&lua_src, lua_table)?;
        let mut out = String::new();
        out.push_str("// AUTO-GENERATED by ffxi-proto/build.rs from msg.lua.\n");
        out.push_str("// Do not edit by hand.\n");
        out.push_str(&format!("pub const {out_const}: &[(u16, &str)] = &[\n"));
        for (id, text) in &entries {
            out.push_str(&format!("    ({id}, {}),\n", rust_string_literal(text)));
        }
        out.push_str("];\n");
        fs::write(out_dir.join(out_file), &out)?;
        println!(
            "cargo:warning=ffxi-proto: scraped {} {} entries",
            entries.len(),
            lua_table_warning_label(lua_table),
        );
    }

    Ok(())
}

fn lua_table_warning_label(table: &str) -> &'static str {
    match table {
        "channel" => "msg_channel",
        "area" => "msg_area",
        "actionModifier" => "msg_action_modifier",
        "system" => "msg_system",
        _ => "msg_<unknown>",
    }
}

/// Slice `xi.msg.<table> = { ... }` out of `msg.lua` and parse each
/// `IDENT = NUM, -- comment` line into `(id, text)`. Same skip rules
/// as the msg_basic header (no comment / sentinel annotation → drop).
/// Hex (`0x..`) literals are accepted; `xi.msg.actionModifier` uses them.
/// Duplicate ids inside one table keep the first text seen.
fn parse_lua_table(src: &str, table: &str) -> Result<Vec<(u16, String)>> {
    let needle = format!("xi.msg.{table} =");
    let header = src
        .find(&needle)
        .with_context(|| format!("could not locate `{needle}` in msg.lua"))?;
    // Skip past the `{` that opens the table body.
    let body_start = src[header..]
        .find('{')
        .with_context(|| format!("no opening `{{` after `{needle}`"))?
        + header
        + 1;
    let body_end = src[body_start..]
        .find('}')
        .with_context(|| format!("no closing `}}` after `{needle}`"))?
        + body_start;
    let body = &src[body_start..body_end];

    let mut out = Vec::new();
    let mut seen = std::collections::HashSet::new();
    for line in body.lines() {
        let line = line.trim();
        let Some(eq) = line.find('=') else { continue };
        let ident = line[..eq].trim();
        if ident.is_empty()
            || !ident.chars().next().is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        {
            continue;
        }
        if !ident.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            continue;
        }
        // After `=`: `<num>,` then optional `-- comment`.
        let tail = &line[eq + 1..];
        let Some(comma) = tail.find(',') else { continue };
        let num_str = tail[..comma].trim();
        let id: u16 = parse_int_lit(num_str).unwrap_or(continue_marker());
        if id == continue_marker() {
            continue;
        }
        let after_comma = &tail[comma + 1..];
        let Some(slash) = after_comma.find("--") else { continue };
        let comment = after_comma[slash + 2..].trim().to_string();
        if comment.is_empty() || is_non_message_annotation(&comment) {
            continue;
        }
        if seen.insert(id) {
            out.push((id, comment));
        }
    }
    if out.is_empty() {
        bail!("parsed zero entries for xi.msg.{table} — msg.lua format may have changed");
    }
    Ok(out)
}

/// Sentinel used by `parse_lua_table` to skip lines whose number didn't
/// parse. `u16::MAX` collides with no real msg id we ship today; if a
/// real id ever lands at 65535 the skip will misfire — change the
/// signal type then.
fn continue_marker() -> u16 {
    u16::MAX
}

fn parse_int_lit(s: &str) -> Option<u16> {
    if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        u16::from_str_radix(hex, 16).ok()
    } else {
        s.parse().ok()
    }
}

/// Parse `msg_basic.h` enum body into `(id, text)` pairs.
///
/// Skipped: lines without a `// ` comment, the `None` sentinel, and
/// "Does not print" / "Display nothing" annotations. The trailing `*/`
/// typo present on a few gardening lines is also stripped.
fn parse_msg_basic(src: &str) -> Result<Vec<(u16, String)>> {
    let mut out = Vec::new();
    for line in src.lines() {
        let line = line.trim();
        // Quickly reject lines that aren't `Ident = N, // ...`.
        let Some(eq) = line.find('=') else { continue };
        // Must be inside the enum body — every entry has a trailing comma.
        let Some(comma) = line[eq..].find(',') else { continue };
        let comma = eq + comma;
        // Identifier ::= [A-Za-z_][A-Za-z0-9_]*
        let ident = line[..eq].trim();
        if ident.is_empty() || !ident.chars().next().is_some_and(|c| c.is_ascii_alphabetic() || c == '_') {
            continue;
        }
        if !ident.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            continue;
        }
        // Number between '=' and ','.
        let num_str = line[eq + 1..comma].trim();
        let id: u16 = match num_str.parse() {
            Ok(n) => n,
            Err(_) => continue,
        };
        // Comment, if any, lives after the first ` // ` past the comma.
        let tail = &line[comma + 1..];
        let Some(slash) = tail.find("//") else { continue };
        let mut comment = tail[slash + 2..].trim().to_string();
        // Strip the stray `*/` typo on a few entries.
        if let Some(stripped) = comment.strip_suffix("*/") {
            comment = stripped.trim_end().to_string();
        }
        if is_non_message_annotation(&comment) {
            continue;
        }
        if comment.is_empty() {
            continue;
        }
        out.push((id, comment));
    }
    if out.is_empty() {
        bail!("parsed zero msg_basic entries — header format may have changed");
    }
    Ok(out)
}

fn is_non_message_annotation(comment: &str) -> bool {
    let low = comment.to_ascii_lowercase();
    // These are author-notes about the enum value, not user-visible strings.
    low.contains("display nothing")
        || low.contains("does not print")
        || low.contains("does not work")
        || low.contains("does nothing")
        || low.starts_with("(assumed")
        || low.starts_with("assumed")
        || low.starts_with("todo")
        || low.starts_with("unused")
}

/// Emit a Rust-source string literal for `s` using a raw string when the
/// content has no `"` or `#`, otherwise an escaped regular string. Keeps
/// FFXI placeholder tokens (`<actor>`, `#`, etc.) verbatim.
fn rust_string_literal(s: &str) -> String {
    if !s.contains('"') && !s.contains('\\') {
        format!("\"{s}\"")
    } else {
        let mut esc = String::with_capacity(s.len() + 2);
        esc.push('"');
        for c in s.chars() {
            match c {
                '"' => esc.push_str("\\\""),
                '\\' => esc.push_str("\\\\"),
                _ => esc.push(c),
            }
        }
        esc.push('"');
        esc
    }
}
